phones/phones/urls.py
from django.contrib import admin
from django.urls import path
from phonesapp.views import *
from phones import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('<str:pk>/edit', edit_number),
    path('files-rostelekom/', parser_rostelecom),
    path('files-avantel/', parser_avantel),
    path('reports/', report),
    path('login/', LoginUser.as_view()),
    path('logout/', logout_user),
    path('report/export_excel', export_excel, name='export_excel'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phones/phonesapp/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.core.validators import FileExtensionValidator
import django


class Parser(models.Model):
    number = models.CharField(max_length=8, verbose_name='Номер', blank=False)
    attachment = models.ForeignKey('Attachments', on_delete=models.CASCADE, verbose_name='Отдел', blank=True, null=True)
    provider = models.ForeignKey('Providers', on_delete=models.CASCADE, verbose_name='Провайдер', blank=False)
    file = models.ForeignKey('Files', on_delete=models.CASCADE, verbose_name='Файл', blank=False)
    date_upload = models.DateField(verbose_name='Дата добавления', blank=False, default=django.utils.timezone.now)
    payment = models.FloatField(verbose_name='Сумма', blank=False)
    result_pay = models.FloatField(verbose_name='Итог', blank=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.number}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Номера парсера'
        verbose_name_plural = 'Номера парсера'


class Numbers(models.Model):
    number = models.CharField(max_length=8, verbose_name='Номер', blank=False)
    attachment = models.ForeignKey('Attachments', on_delete=models.CASCADE, verbose_name='Отдел', null=True, blank=True)
    comment = models.CharField(max_length=500, verbose_name='Комментарий', blank=True)
    date_attach = models.DateField(verbose_name='Дата прикрепления', blank=True, null=True)
    cf = models.BooleanField(default=False, verbose_name='ЦФ', blank=False)
    is_enabled = models.BooleanField(default=True, verbose_name='Активен', blank=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.number}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Номера'
        verbose_name_plural = 'Номера'


class Files(models.Model):
    file = models.FileField(upload_to='./static' + 'files' + '/%Y/%m/', verbose_name='Файлы', blank=False,
                            validators=[FileExtensionValidator(['xls', 'xlsx'])])
    provider = models.ForeignKey('Providers', on_delete=models.CASCADE, verbose_name='Провайдер', blank=False)
    date_upload = models.DateField(auto_now_add=True, verbose_name='За месяц', blank=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.file}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Файлы'
        verbose_name_plural = 'Файлы'


class Providers(models.Model):
    provider = models.CharField(max_length=50, verbose_name='Провайдер', blank=False)
    is_enabled = models.BooleanField(default=True, verbose_name='Активен', blank=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.provider}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Провайдера'
        verbose_name_plural = 'Провайдеры'


class Attachments(models.Model):
    attachment = models.CharField(max_length=200, verbose_name='Отделение', blank=False)
    is_enabled = models.BooleanField(default=True, verbose_name='Активен', blank=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.attachment}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Отделы'
        verbose_name_plural = 'Отделы'


class SubscriptionFee(models.Model):
    summ = models.FloatField(verbose_name='Абонентская плата', blank=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.summ}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Абон. плата'
        verbose_name_plural = 'Абон. плата'

phones/phonesapp/forms.py
from .models import Numbers, Files
from django.forms import ModelForm, FileInput, Select, TextInput, Textarea, CheckboxInput, DateInput


class NumbersForm(ModelForm):
    class Meta:
        model = Numbers
        fields = ['number', 'attachment', 'comment', 'date_attach', 'cf']
        widgets = {
            'number': TextInput(attrs={'class': 'form-control', 'style': 'width: 300px;'}),
            'attachment': Select(attrs={'class': 'form-select', 'style': 'width: 300px;'}),
            'comment': Textarea(attrs={'class': 'form-control', 'style': 'width: 500px; resize: none;', 'cols': '50',
                                       'rows': '5'}),
            'date_attach': DateInput(format='%d/%m/%Y', attrs={'class': 'form-control', 'style': 'width: 300px;', 'id': 'datepicker'}),
            'cf': CheckboxInput,
        }


class AddFiles(ModelForm):
    class Meta:
        model = Files
        fields = ['file', 'provider']
        widgets = {
            'file': FileInput(attrs={'class': 'form-control', 'style': 'width: 350px'}),
            'provider': Select(attrs={'type:': 'file', 'class': 'form-select', 'style': 'width: 350px;'})
        }

phones/phonesapp/views.py
import pandas
from django.http import HttpResponse
import datetime
import xlwt
from .models import Numbers, Attachments, Files, Providers, Parser, SubscriptionFee
from django.core.paginator import Paginator
from .filters.filters import NumbersFilter, ReportFilter
from django.shortcuts import render, redirect
from .forms import NumbersForm, AddFiles
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, permission_required
import pandas as pd


class LoginUser(LoginView):

    form_class = AuthenticationForm
    template_name = 'login/login.html'


def logout_user(request):

    logout(request)
    return redirect('/login')


@login_required(login_url='login/')
@permission_required('phonesapp.view_numbers')
def home(request):

    number = Numbers.objects.exclude(is_enabled=False)
    attachment = Attachments.objects.all()
    my_filter = NumbersFilter(request.GET, queryset=number)
    number = my_filter.qs

    m = []
    k = 0
    for i in number:
        k += 1
        m.append(k)

    numbers_sum = len(m)
    numbers_cf = len(Numbers.objects.exclude(cf=False))
    numbers_hide = len(Numbers.objects.exclude(is_enabled=True))

    paginator = Paginator(number, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    paginator_obj = Paginator(m, 15).get_page(page_number)

    context = {
               'number': number,
               'page_obj': page_obj,
               'paginator_obj': paginator_obj,
               'numbers_sum': numbers_sum,
               'numbers_cf': numbers_cf,
               'numbers_hide': numbers_hide,
               'attachment': attachment,
               }

    return render(request, 'home/home.html', context)


@login_required(login_url='login/')
@permission_required('phonesapp.change_numbers')
def edit_number(request, pk):

    numbers = Numbers.objects.get(id=pk)
    form = NumbersForm(instance=numbers)

    if request.method == 'POST':
        form = NumbersForm(request.POST, instance=numbers)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'edit/edit.html', context)


@login_required(login_url='login/')
@permission_required('phonesapp.add_parser')
def parser_rostelecom(request):

    files = Files.objects.all()
    providers = Providers.objects.get(id=1)

    if request.method == 'POST':
        form = AddFiles(request.POST, request.FILES)
        if form.is_valid():

            i = Files(**form.cleaned_data)
            i.save()

            last_file = (Files.objects.order_by('id').last()).id
            excel_file = Files.objects.get(pk=last_file)
            excel_file_str = str(excel_file)

            file = pandas.read_excel('media/' + excel_file_str)
            number_summ = file[['Телефон А', 'Сумма']]
            result = number_summ.groupby('Телефон А').sum()

            temp = []
            sub_fee = float(str(SubscriptionFee.objects.get(pk=1)))

            base_cf = str(Numbers.objects.filter(cf=True))
            base_no_cf = str(Numbers.objects.filter(cf=False))

            for index, row in result.iterrows():
                str_index = str(index).lstrip("'3822")

                if str_index in base_cf:
                    str_index_number = Numbers.objects.get(number=str_index)
                    str_index_attach = str_index_number.attachment
                    Parser(number=str_index,
                           attachment=str_index_attach,
                           provider=providers,
                           file=Files.objects.order_by('id').last(),
                           payment=row['Сумма'],
                           result_pay=row['Сумма']).save()
                elif str_index in base_no_cf:
                    str_index_number = Numbers.objects.get(number=str_index)
                    str_index_attach = str_index_number.attachment
                    Parser(number=str_index,
                           attachment=str_index_attach,
                           provider=providers,
                           file=Files.objects.order_by('id').last(),
                           payment=row['Сумма'],
                           result_pay=row['Сумма'] + sub_fee).save()
                elif str_index not in str(Numbers.objects.all()):
                    temp.append(str_index)
                    Parser(number=str_index,
                           attachment=None,
                           provider=providers,
                           file=Files.objects.order_by('id').last(),
                           payment=row['Сумма'],
                           result_pay=row['Сумма']).save()

            return render(request, 'files/rostelecom.html', {'alert_flag': True, 'temp': temp})

    else:
        form = AddFiles()

    context = {'form': form, 'providers': providers, 'files': files}

    return render(request, 'files/rostelecom.html', context)


@login_required(login_url='login/')
@permission_required('phonesapp.add_parser')
def parser_avantel(request):

    files = Files.objects.all()
    providers = Providers.objects.get(id=2)

    if request.method == 'POST':
        form = AddFiles(request.POST, request.FILES)
        if form.is_valid():

            i = Files(**form.cleaned_data)
            i.save()

            last_file = (Files.objects.order_by('id').last()).id
            excel_file = Files.objects.get(pk=last_file)
            excel_file_str = str(excel_file)

            file = pandas.read_excel('media/' + excel_file_str, skiprows=1)
            number_summ = file[['Номер звонящего', 'Стоимость']]
            result = number_summ.groupby('Номер звонящего').sum()

            temp = []
            sub_fee = float(str(SubscriptionFee.objects.get(pk=1)))

            base_cf = str(Numbers.objects.filter(cf=True))
            base_no_cf = str(Numbers.objects.filter(cf=False))

            for index, row in result.iterrows():
                str_index = str(index).lstrip("'3822")

                if str_index in base_cf:
                    str_index_number = Numbers.objects.get(number=str_index)
                    str_index_attachment = str_index_number.attachment
                    Parser(number=str_index,
                           attachment=str_index_attachment,
                           provider=providers,
                           file=Files.objects.order_by('id').last(),
                           payment=row['Стоимость'],
                           result_pay=row['Стоимость'] + sub_fee).save()
                elif str_index in base_no_cf:
                    str_index_number = Numbers.objects.get(number=str_index)
                    str_index_attachment = str_index_number.attachment
                    Parser(number=str_index,
                           attachment=str_index_attachment,
                           provider=providers,
                           file=Files.objects.order_by('id').last(),
                           payment=row['Стоимость'],
                           result_pay=row['Стоимость']).save()
                if str_index not in str(Numbers.objects.all()):
                    temp.append(str_index)
                    Parser(number=str_index,
                           attachment=None,
                           provider=providers,
                           file=Files.objects.order_by('id').last(),
                           payment=row['Стоимость'],
                           result_pay=row['Стоимость']).save()

            return render(request, 'files/avantel.html', {'alert_flag': True, 'temp': temp})

    else:
        form = AddFiles()

        context = {'form': form, 'providers': providers, 'files': files}

        return render(request, 'files/avantel.html', context)


@login_required(login_url='login/')
def report(request):

    numbers_pars = Parser.objects.all()
    attachments = Attachments.objects.all()
    myFilter = ReportFilter(request.GET, queryset=numbers_pars)
    numbers_pars = myFilter.qs
    context = {'numbers_pars': numbers_pars, 'ReportFilter': myFilter, 'attachments': attachments}

    return render(request, 'report/report.html', context)


def export_excel(request):

    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = ("attachment; filename=Numbers_" + str(datetime.datetime.now().strftime("%d/%m/%y")) + '.xls')
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Numbers', cell_overwrite_ok=True)
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['Отдел',
               'Номер',
               'К оплате']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    rows = ReportFilter(request.GET,
                        queryset=Parser.objects.all().values_list(
                            'attachment__attachment',
                            'number',
                            'result_pay')).qs

    res = pd.DataFrame(ReportFilter(request.GET, queryset=Parser.objects.annotate().values_list('result_pay')).qs)
    res_sum = res.sum()
    itog = float(res_sum.to_numpy())

    for row in rows:
        row_num += 1

        for col_num in range(len(row)):

            if isinstance(row[col_num], datetime.datetime):
                date_time = row[col_num].astimezone(datetime.timezone(datetime.timedelta(hours=7))).strftime('%d/%m/%Y %H:%M')
                ws.write(row_num, col_num, date_time, font_style)
                ws.write_merge(1, row_num, 0, 0, f'{str(row[0])}')

            else:
                ws.write(row_num, col_num, row[col_num], font_style)
                ws.write_merge(1, row_num, 0, 0, f'{str(row[0])}')
                ws.write(row_num+1, 1, 'Итог:')
                ws.write(row_num + 1, 2, itog)

phones/phonesapp/templates/home/home.html
{% extends 'base/base.html' %}
{% block content %}
{% csrf_token %}
{% load poll_extras %}
<link rel="stylesheet" href="media/static/autocomplete/css/style.css" xmlns="http://www.w3.org/1999/html">
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>

<link href="/media/static/tablesort/css/sortable.min.css" rel="stylesheet">
<script src="/media/static/tablesort/js/sortable.min.js"></script>

<br>
<h2>
    Список номеров
</h2>
<br>
Общее количество номеров: {{ numbers_sum }}<br>
Номеров ЦФ: {{ numbers_cf }}<br>
Неактивных номеров: {{ numbers_hide }}<br>
<br>
<div class="card" style="width: 900px;"><h5
        class="card-header">Поиск по номерам:</h5>
    <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">Введите один или несколько параметров:</h6>
        <div class="d-flex">
            <form method="get">
                <div class="row">
                    <div class="col">
                        <input class="form-control"
                               type="number"
                               name="id"
                               id="id_id"
                               placeholder="ID"
                               aria-label="default input example">
                    </div>
                    <div class="col">
                        <input class="form-control"
                               type="number"
                               name="number"
                               id="id_number"
                               style="width: 180px;"
                               placeholder="Номер телефона"
                               aria-label="default input example">
                    </div>
                    <div class="col">
                        <select name="attachment"
                                class="form-select"
                                style="width: 280px;"
                                id="id_attachment">
                            <option value="" selected="">---Прикрепление---</option>
                            {% for item in attachment %}
                                <option value="{{ item.id }}">{{ item.attachment }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col">
                        <label for="id_cf" class="form-label">ЦФ</label>
                        <input type="checkbox"
                               name="cf"
                               id="id_сf">
                        <script>
                            $('#id_сf').change(function(){
                                $(this).val('true');
                            });
                        </script>
                    </div>
                    <div class="col mx-3">
                        <button class="btn btn-primary" type="submit">Поиск</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
<!---------Таблица начало---------->
<!--<table id="MyTable" class="table table-bordered">-->
{% if request.user|has_group:"admins" %}
<table id="MyTable" class="table sortable table-bordered" style="border-color: black; width: 100%">
    <thead>
    <!---------Заголовки----------->
    <tr>
        <th>ID</th>
        <th>Номер</th>
        <th>Прикрепление</th>
        <th>Дата прикрепления</th>
        <th>Комментарий</th>
        <th>ЦФ</th>
    </tr>
    </thead>
    <!----------------------------->
    <!-----------Ячейки таблицы---->
    <tbody>
    {% for item in page_obj %}
    <tr>
        <td><a href="{{ item.id }}/edit">{{ item.id }}</a></td>
        <td>{{ item.number }}</td>
        <td>{{ item.attachment.attachment }}</td>
        <td>{{ item.date_attach }}</td>
        <td>{{ item.comment }}</td>
        <td>{{ item.cf|yesno:"ЦФ, " }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<table id="MyTable" class="table sortable table-bordered" style="border-color: black; width: 100%">
    <thead>
    <!---------Заголовки----------->
    <tr>
        <th>Номер</th>
        <th>Прикрепление</th>
        <th>Дата прикрепления</th>
        <th>Комментарий</th>
        <th>ЦФ</th>
    </tr>
    </thead>
    <!----------------------------->
    <!-----------Ячейки таблицы---->
    <tbody>
    {% for item in page_obj %}
    <tr>
        <td>{{ item.number }}</td>
        <td>{{ item.attachment.attachment }}</td>
        <td>{{ item.date_attach }}</td>
        <td>{{ item.comment }}</td>
        <td>{{ item.cf|yesno:"ЦФ, " }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
<br>
{% include 'home/pagination.html' %}
<br>
{% endblock %}

phones/phonesapp/templates/home/pagination.html
{% load poll_extras %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if paginator_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% my_url 1 'page' request.GET.urlencode %}">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% my_url paginator_obj.previous_page_number 'page' request.GET.urlencode %}">&lt;</a>
        </li>
        {% endif %}

        {% if paginator_obj.number|add:'-4' > 1 %}
        <li class="page-item">
            <a class="page-link" href="{% my_url paginator_obj.number|add:'-5' 'page' request.GET.urlencode %}">&hellip;</a>
        </li>
        {% endif %}

        {% for i in paginator_obj.paginator.page_range %}
        {% if paginator_obj.number == i %}
        <li class="page-item active" aria-current="page">
            <span class="page-link">{{ i }}/{{ paginator_obj.paginator.num_pages}}
              <span class="sr-only"></span>
            </span>
        </li>

        {% elif i > paginator_obj.number|add:'-5' and i < paginator_obj.number|add:'5' %}
        <li class="page-item"><a class="page-link" href="{% my_url i 'page' request.GET.urlencode %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if paginator_obj.paginator.num_pages > paginator_obj.number|add:'4' %}
        <li class="page-item"><a class="page-link" href="{% my_url paginator_obj.number|add:'5' 'page' request.GET.urlencode %}">&hellip;</a></li>
        {% endif %}

        {% if paginator_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% my_url paginator_obj.next_page_number 'page' request.GET.urlencode %}">&gt;</a>
        </li>
        <li class="page-item">
            <a class='page-link' href="{% my_url paginator_obj.paginator.num_pages 'page' request.GET.urlencode %}"> &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>